# Form implementation generated from reading ui file 'instagram_login.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"stop:0 #833ab4, stop:0.5 #fd1d1d, stop:1 #fcb045);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(160, 60, 300, 400))
        self.frame.setStyleSheet("background-color: #111;\n"
"border-radius: 10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.labelLogo = QtWidgets.QLabel(parent=self.frame)
        self.labelLogo.setGeometry(QtCore.QRect(100, 50, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Script")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.labelLogo.setFont(font)
        self.labelLogo.setStyleSheet("color: white;\n"
"font-size: 25pt;\n"
"font-family: \"Script\";\n"
"")
        self.labelLogo.setObjectName("labelLogo")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(90, 160, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 200, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEditUsername = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEditUsername.setGeometry(QtCore.QRect(30, 140, 231, 31))
        self.lineEditUsername.setStyleSheet("background-color: #262626;\n"
"color: white;\n"
"border: 1px solid #3E3E3E;\n"
"border-radius: 4px;\n"
"padding: 6px;\n"
"font-size: 8pt;\n"
"")
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.ineEditPassword = QtWidgets.QLineEdit(parent=self.frame)
        self.ineEditPassword.setGeometry(QtCore.QRect(30, 180, 231, 31))
        self.ineEditPassword.setStyleSheet("background-color: #262626;\n"
"color: white;\n"
"border: 1px solid #3E3E3E;\n"
"border-radius: 4px;\n"
"padding: 6px;\n"
"font-size: 8pt;\n"
"")
        self.ineEditPassword.setObjectName("ineEditPassword")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(160, 220, 111, 16))
        self.label.setStyleSheet("color: #0095F6;\n"
"")
        self.label.setObjectName("label")
        self.btnLogin = QtWidgets.QPushButton(parent=self.frame)
        self.btnLogin.setGeometry(QtCore.QRect(40, 250, 211, 21))
        self.btnLogin.setStyleSheet("background-color: #0095F6;\n"
"color: white;\n"
"font-weight: bold;\n"
"border: none;\n"
"border-radius: 4px;\n"
"padding: 6px;\n"
"")
        self.btnLogin.setObjectName("btnLogin")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(140, 280, 47, 13))
        self.label_2.setStyleSheet("color: white;\n"
"font-size: 6pt;\n"
"")
        self.label_2.setObjectName("label_2")
        self.btnFacebookLogin = QtWidgets.QPushButton(parent=self.frame)
        self.btnFacebookLogin.setGeometry(QtCore.QRect(80, 300, 131, 16))
        self.btnFacebookLogin.setStyleSheet("color: #385185;\n"
"font-weight: bold;\n"
"")
        self.btnFacebookLogin.setObjectName("btnFacebookLogin")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(50, 360, 141, 21))
        self.label_3.setStyleSheet("\n"
"color: white;\n"
"font-weight: bold;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setGeometry(QtCore.QRect(190, 360, 47, 21))
        self.label_4.setStyleSheet("color: #0095F6;")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelLogo.setText(_translate("MainWindow", "Instagram"))
        self.lineEditUsername.setPlaceholderText(_translate("MainWindow", "Phone number, username or email address"))
        self.ineEditPassword.setPlaceholderText(_translate("MainWindow", "password"))
        self.label.setText(_translate("MainWindow", "Forgotten password?"))
        self.btnLogin.setText(_translate("MainWindow", "Log In"))
        self.label_2.setText(_translate("MainWindow", "OR"))
        self.btnFacebookLogin.setText(_translate("MainWindow", "Log in with Facebook"))
        self.label_3.setText(_translate("MainWindow", "Don\'t have an account?"))
        self.label_4.setText(_translate("MainWindow", "Sign Up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
